dist: xenial
sudo: required
language: cpp
compiler: gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-default libjack-jackd2-dev libsamplerate0-dev libavformat-dev libavcodec-dev libavutil-dev libasound2-dev qtmultimedia5-dev libqt5multimedia5-plugins libboost-all-dev libfftw3-dev
  - git clone https://github.com/jrosener/libKeyFinder.git
  - cd libKeyFinder && qmake && make && sudo make install
  - cd ..
script:
  - cd libdigitalscratch && qmake && make && sudo make install
  - make clean && qmake CONFIG+=test && make
  - ./libdigitalscratch-test
  - cd ..
  - cd digitalscratch && qmake && make
  - make clean && qmake CONFIG+=test-no_device_test && make
  - ./digitalscratch-test
